[package]
name = "timezones"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.6"
regex = "1"
serde = "*"
serde_json = "*"
serde_derive = "*"
